version: "3.9"
services:
  api-service:
    build: ./Template-Api
    ports:      
      - 4000:80
      - 4001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db-service
  db-service:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      SA_PASSWORD: "BKaJmeWhE9THpS3uxNUphqHwvSvQwPLwUhp6JKcx9WNTr3uwtFVXBF9H4W5aJthDgtrSv9"
      ACCEPT_EULA: "Y"
  





  